# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
  - page: home
    url: /
    icon:
  - page: 项目资源
    url: /categories/项目资源/
    icon:
  - page: 商业案例
    url: /categories/商业案例/
    icon:
#  - page: 项目分享
#    url: /categories/项目分享/
#    icon:
#  - page: 薅羊毛
#    url: /categories/薅羊毛/
#    icon:
#  - page: 历史上的今天
#    url: /categories/历史上的今天/
#    icon:
  - page: 技术教程
    url: /categories/技术教程/
    icon:
  - page: 时间轴
    url: /archives/
    icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: "./img/head-img.jpg"
  url: "https://www.myyhq.top"

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends

## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
#  <p>
#      主题下载：<a href="https://github.com/shenliyang/hexo-theme-snippet" title="fork me" target="_blank">Snippet主题</a> <br/>
#      主题使用：<a href="https://github.com/shenliyang/hexo-theme-snippet/blob/master/README.md#常见问题" title="" target="_blank">常见使用问题</a> <br/>
#      支持主题：<a href="https://github.com/shenliyang/hexo-theme-snippet/stargazers">Star一下</a>
#  </p>

## 社交设置
social:
  - name: Github
    icon: git
    href: //github.com/i-stack
  - name: 邮箱
    icon: envelope-o
    href: mailto:672030963@qq.com
  - name: 联系QQ
    icon: qq
    href: /
  - name: 微信
    icon: weixin
    href: i-stack
#  - name: QQ群
#    icon: users
#    href: /
#  - name: RSS
#    icon: feed
#    href: /atom.xml

## 文章分类设置
cate_config:
  show_count: true
  show_current: true

## 文章归档设置
arch_config:
  type: "monthly"
  format: "YYYY年MM月"
  show_count: true
  order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: "#444"
  outlineMethod: "block"
  outlineColour: "#FFDAB9"
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - 商城淘券儿: https://www.myyhq.top

# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
  img: https://hexo-theme-snippet-1251680922.cos.ap-beijing.myqcloud.com/img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 64

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 3000
  text: "本文于%d天之前发表，文中内容可能已经过时。"

## 文章内声明
declaration:
  enable: true
  title: "转载声明"
  tip: |-
    商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://i-stack.github.io/" target="_blank">大唐盛世</a>

## 文章打赏
reward:
  alipay: "/img/alipay.png"
  wepay: "/img/wechat.png"
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## utterances评论
utterances:
  enable: false
  repo: shenliyang/snippet-comment
  issueTerm: pathname
  issueNumber:
  theme: github-light
  label:
  cdn:

## Valine评论
valine:
  enable: false
  appId: iv509cTC3tfhBFipoZZ2rXA1-gzGzoHsz
  appKey: JrOm1nDA1m2Y376YU9h9LvbA
  placeholder: 说点什么吧
  notify: false
  verify: false
  avatar: mm
  meta: nick,mail
  pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: true
  appid: cywx8yBY9
  conf: prod_4295944241e2145f25f438e04b2ed613

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
  enable: false
  clientID:
  clientSecret:
  repo:
  owner:
  admin:
  perPage:
  distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

## 网站访客统计
visit_counter:
  site: true
  page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics:

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification: codeva-7tnz9mgYod

### 百度自动推送
baidu_push: true

#网站主题配置
since: 2020
beian: '豫ICP备2022028466号'
robot: "all" ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.3.0
